# move mode: profile position (0), homing (1), continuous positioning (2)
int8 mode 0

# profile parameters
float64 profile_velocity 0
float64 profile_acceleration 0
float64 profile_deceleration 0

# abs. or rel. move (mode: 0)
bool absolute_relative 1

# target position (mode: 0)
float64 target_position 0

# target position topic name (mode: 2)
string target_position_topic "target_position"

# homing method and offset (mode: 1)
int8    method 35
---
---
float64 actual_position 0
float64 target_position 0

